apiVersion: 1
groups:
    - orgId: 1
      name: monitoring-health
      folder: Platform
      interval: 1m
      rules:
          - uid: monitoring-target-down
            title: Monitoring target down
            condition: A
            data:
                - refId: A
                  queryType: ""
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: prometheus
                  model:
                      refId: A
                      expr: up{job=~"alloy|loki|tempo|grafana"} == 0
                      instant: true
                      interval: ""
                      intervalMs: 1000
                      maxDataPoints: 43200
            noDataState: NoData
            execErrState: Error
            for: 5m
            annotations:
                summary: A monitoring component is unreachable to Prometheus.
            labels:
                severity: warning
